cluster:
  name: puppetmaster
  id: 0

k8sServiceHost: "192.168.2.181"
k8sServicePort: "6443"

kubeProxyReplacement: true

operator:
  # Can't have more replicas than nodes
  replicas: 1
  rollOutPods: true

# Roll out cilium agent pods automatically when ConfigMap is updated.
rollOutCiliumPods: true

debug:
  enabled: false

# Increase rate limit when doing L2 announcements
k8sClientRateLimit:
  qps: 20
  burst: 100

l2announcements:
  enabled: true

externalIPs:
  enabled: true

enableCiliumEndpointSlice: true

gatewayAPI:
  enabled: true

hubble:
  enabled: false
  relay:
    enabled: false
    rollOutPods: false
  ui:
    enabled: false
    rollOutPods: true
